/* Generated by bin2c, do not edit manually */
#ifndef __arnold_h_included
#define __arnold_h_included
#include <stdint.h>
/* Contents of file arnold.png */
extern const size_t arnold_png_size;
extern uint8_t arnold_png[396501];

#endif    /* __arnold_h_included */
